### ISSUE TITLE
No module named 'werkzeug.contrib'

### ISSUE THREAD

**Issue by jdbancal** [replab/replab#218]
I'm trying to clean a few things in the documentation, but I don't manage to recompile it with sphinx. I get the following error, related 

```
>> replab_generate sphinxbuild
Crawling code base
Folder 'docs' exists in '/home/bancal/Sync/Matlab_pour_lrs/libraries/replab', will be deleted
Running Sphinx
Running sphinx-build -b html sphinx docs
Running Sphinx v2.4.1

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/bancal/Sync/Matlab_pour_lrs/libraries/replab/sphinxdocs/sphinx2/lib/python3.7/site-packages/sphinx/config.py", line 348, in eval_config_file
    execfile_(filename, namespace)
  File "/home/bancal/Sync/Matlab_pour_lrs/libraries/replab/sphinxdocs/sphinx2/lib/python3.7/site-packages/sphinx/util/pycompat.py", line 81, in execfile_
    exec(code, _globals)
  File "/home/bancal/Sync/Matlab_pour_lrs/libraries/replab/sphinx/conf.py", line 120, in <module>
    import ablog
  File "/home/bancal/Sync/Matlab_pour_lrs/libraries/replab/sphinxdocs/sphinx2/lib/python3.7/site-packages/ablog/__init__.py", line 8, in <module>
    from .post import (
  File "/home/bancal/Sync/Matlab_pour_lrs/libraries/replab/sphinxdocs/sphinx2/lib/python3.7/site-packages/ablog/post.py", line 16, in <module>
    from werkzeug.contrib.atom import AtomFeed
ModuleNotFoundError: No module named 'werkzeug.contrib'
```

Notice that I did run `pip install ablog werkzeug`. Not sure what is missing... The current error prevents the creation of any html output (including what is not related to the blog). And if I comment out the 'ablog'-related elements in `replab/sphinx/conf.py`, the site building hangs later, where it realizes it cannot find the blog pages...

Any idea how to avoid the above error (using python 3.7.3)?

**Comment by jdbancal** [comment]
I observe the same issue when running the command `replab_generate sphinxbuild` from an instance of octave 5.1.0 launched within a python3 virtualenv (on ubuntu 18.10)
